[package]
name = "uniflow"
version = "0.1.0"
edition = "2024"

[dependencies]
reactive_graph = { version = "0.2.12", features = ["effects"] }
tokio = { version = "1.49.0", features = ["sync", "rt"] }
